### ISSUE TITLE
Freeze Wizard: second attempt fixes

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#603] opened 2022-04-11 10:28 UTC
After some more discussions:

- keep the PRs for freezing spec, but allow inputting *labels* and automatically filling in the PRs
- instead of *staging* the PRs, immediately cherrypick the commits on the freeze branch during the wizard's execution
- add similar feature for the master branch, with a "bump" sequence

**Comment by xmo-odoo** [comment] 2022-04-11 10:29
/cc @d-fence @Xavier-Do 

One more possibility but less sure: integrate the update of master's release commits?

**Comment by Xavier-Do** [comment] 2022-04-11 13:19
More than a direct opinion on the proposed soltion, I'll try to make a summary of critical points for runbot when freezing. In this example, we are freezing saas-15.3

Testing odoo, entertprise, ... is not an issue  since it is almost version independant. The only really problematic point is **upgrade**. But there are still some points to check regarding version:

- Runbot must use the correct **docker image**. It could be automatically done but is still a manual operation.
- Other build should use a **reference done batch** to define the commit to use to fill missing commits (odoo when testing enterprise, ...) So it is always better to have a green, consistent, well freezed 15.3 before testing other 15.3 branches. Before that it will use the master or the current 15.3 founds heads withc is almost ok but not perfect.

Regarding upgrades: 

The current behaviour of runbot is to use the `runbot.version` object to define the version to test when testing upgrades.
The version tested are the last saas, and the last versions. Before the freeze upgrade are tested for transitions 

- _15.0-> master_
- _saas-15.2-> master_
This is defined in the step [**upgrade_to_current_with_tests** ](https://runbot.odoo.com/web/#id=237&action=535&model=runbot.build.config.step&view_type=form&cids=&menu_id=405)
Last saas and major version are checked.

Since the master is the future 15.3, the upgrade 15.2-> 15.3 is already tested, (kind of, the realease.py will slightly change) but the upgrade 15.3-> master (mastert-master) is not  tested. In rare case, this can break.
Moreover, once any saas-15.3 is pushed, the version exists, but no batch is currently `done` fort this version, and there is no correct reference batch to test upgrade from 15.3 to master. This means that for a short perdiod, only 15.0->master is tested. A solution can be to test all intermediate in **upgrade_to_current_with_tests**  but more saas we have, more load there is. This could be mitigate some ways, but the current idea was that the freeze should be as fast as possible to avoid this problematic transition. This is also why disabling the mergebot and forwardport bot during this phase allows to have a kind of transactional transition between the beginning and the end of the freeze by bloking any merge during this phase.

What is a finished freeze imho:
-> All expected master pr are merged, no staging in progress. Ideally, the last master batch is finished to be sure that the 15.3 templates will be tested with the right version
-> All [REL] commit are pushed on new 15.3 branches, triggering the runbot.version creation + the reference batch is building using all new head. 
-> At the same time, the odoo/master is pushed with the new odoo release.py, a new batch is tested with this version. 
-> at this point to be 100% sure that everything is correct, we need to wait fot the 15.3 to be done and templates to be green + upgrade un master to be green. It may need a new batch in rare cases to ensure that the last master and last saas are tested with the correct heads. Is somthing breaks, it should be fixed by disabling tests or adding upgrade exception or pushing a fix waiting for a proper investigation. 
Side note: the idea of having cross version batches may solve this issue but this is a topic for another day. 
-> At this point we know for sure that the 15.4 and master works together and all templates are available and we can let the mergebot and forwardport bot work again. 

Why I would prefer to have the fasted, more transactionnal and less complicated merge process possible: 
Most of the time there wont be any bugs regarding 15.3->master upgrades, but in some cases the template installation will fail (no demo installation  is not tested in master by default) or some unexpected behaviour break once 15.3 is modified to 15.4 (`assert version < (15,4)` as a dummy example ). Those problem are rare but more stresfull to manage when there is 200 pending and 30 breaking auto generated forwardport pr. Having morte possible combination of 15.3 commis makes it also a little more complicated to debug if something breaks: is it just that the current state is inconsistent (missing commit in master breaking templates, the upgrade where not tested as expected) or do we have a _real_ bug in 15.3->15.4 upgrade.

**Closed** 2022-08-24 06:40 UTC
Labels: mergebot, forwardbot
